cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn global add coveralls
  - yarn install

language: node_js
node_js:
  - '10'

script:
  - yarn test:ci | coveralls ; test ${PIPESTATUS[0]} -eq 0
